<a href="https://colab.research.google.com/github/ETorresSacha/Analisis-de-datos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# Crear arreglo de 1 dimensión con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print('Arreglo 1D:', arr1)
print('Forma (shape):',arr1.shape)
print('Tipo de datos (dtype):',arr1.dtype)

Arreglo 1D: [1 2 3 4 5 6]
Forma (shape): (6,)
Tipo de datos (dtype): int64


In [6]:
# Cambiar la forma del arreglo a una matriz 2x3
arr2 =arr1.reshape(2,3) # fila, columna
print('Arreglo 2D:\n', arr2)
print('Forma (shape):',arr2.shape)
print('Tipo de datos (dtype):',arr2.dtype)

Arreglo 2D:
 [[1 2 3]
 [4 5 6]]
Forma (shape): (2, 3)
Tipo de datos (dtype): int64


In [9]:
# Crear una matriz con forma (4,4) con números aleatorios entre 0 y 1.
matrix = np.random.rand(4,4)
print('Arreglo 2D:\n', matrix)
print('Forma (shape):',matrix.shape)
print('Tipo de datos (dtype):',matrix.dtype)

Arreglo 2D:
 [[0.6427135  0.22236642 0.69184484 0.24013331]
 [0.44292743 0.79700337 0.8219627  0.9284945 ]
 [0.88384404 0.5776948  0.52429535 0.18780737]
 [0.53686441 0.25302666 0.84747845 0.72856485]]
Forma (shape): (4, 4)
Tipo de datos (dtype): float64


In [11]:
import random

# Generar un número aleatorio entre 0 y 1
num_aleatorio = random.random()
print(f"random.random:Número aleatorio entre 0 y 1: {num_aleatorio}")

# Generar un entero aleatorio entre 1 y 10
numero_entero = random.randint(1, 10)
print(f"random.randint:Entero aleatorio entre 1 y 10: {numero_entero}")

# Generar un número flotante aleatorio entre 5.0 y 10.0
numero_flotante = random.uniform(5.0, 10.0)
print(f"random.uniform:Número flotante aleatorio entre 5.0 y 10.0: {numero_flotante}")

# Seleccionar un elemento aleatorio de una lista
colores = ["rojo", "azul", "verde"]
color_elegido = random.choice(colores)
print(f"random.choice:Color elegido aleatoriamente: {color_elegido}")

# Mezclar una lista
numeros = [1, 2, 3, 4, 5]
random.shuffle(numeros)
print(f"random.shuffle:Lista mezclada: {numeros}")

# Seleccionar 2 elementos aleatorios sin reemplazo de una lista
elementos = ['a', 'b', 'c', 'd', 'e']
muestra = random.sample(elementos, 2)
print(f"random.sample:Muestra aleatoria de elementos: {muestra}")

# Inicializar el generador de números aleatorios para reproducibilidad
random.seed(42)
print(f"random.seed:Número aleatorio con semilla 42: {random.random()}")

random.random:Número aleatorio entre 0 y 1: 0.025010755222666936
random.randint:Entero aleatorio entre 1 y 10: 5
random.uniform:Número flotante aleatorio entre 5.0 y 10.0: 6.224459269017381
random.choice:Color elegido aleatoriamente: rojo
random.shuffle:Lista mezclada: [4, 2, 3, 5, 1]
random.sample:Muestra aleatoria de elementos: ['a', 'e']
random.seed:Número aleatorio con semilla 42: 0.6394267984578837


In [12]:
# Crear un arreglo de 2 dimensiones a partir de una lista de listas
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [13]:
# Crear un arreglo de ceros con una forma (3,4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# Crear un arreglo con unos con una forma(2,2)
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [16]:
# Modificar una matriz
arr = np.ones((2,2))
arr[1,1] =10
arr

array([[ 1.,  1.],
       [ 1., 10.]])

In [17]:
# Crear una matriz identidad
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# Crear un arreglo 3d de ceros con forma (2,3,4)
arr = np.zeros((2,3,4)) # genera 2 matrices de 3x4 cada uno
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
# Modificar una matris en 3d
arr = np.zeros((2,3,4)) # genera 2 matrices de 3x4 cada uno
arr[0,1,2]=5 # toma  de la matriz en la posición 0, la fila 1 y la columna 2 y modifica
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
# Transpuesta de array
arr = np.random.rand(2,5)
arr

array([[0.79010755, 0.24679403, 0.03264802, 0.65702635, 0.54349799],
       [0.20417247, 0.5544747 , 0.16728427, 0.65910943, 0.1561854 ]])

In [24]:
arr.T

array([[0.79010755, 0.20417247],
       [0.24679403, 0.5544747 ],
       [0.03264802, 0.16728427],
       [0.65702635, 0.65910943],
       [0.54349799, 0.1561854 ]])

In [26]:
# concat de array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr1,arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [30]:
# Concatenar arreglos horizontalmente
arr_h = np.hstack((arr1,arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
# Concatenar arreglos verticalmente
arr_v = np.vstack((arr1,arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])